---
# ansible_role_gnome_minimal/tasks/fedora.yml
# Author: MTO 
# Description: Minimal installation of Gnome on Fedora.
#
- name: Gnome Minimal - Install Gnome Minimal (Fedora)
  dnf:
    name:
      - gnome-shell
    state: present    
  
- name: Gnome Minimal - Get default runlevel (Fedora)
  command: systemctl get-default
  register: runlevel
  
- name: Gnome Minimal - Set graphical runlevel (Fedora)
  command: systemctl set-default graphical.target
  when: runlevel.stdout != "graphical.target"
  
- name: Gnome Minimal - Is graphical currently active (Fedora)
  command: systemctl is-active graphical.target
  ignore_errors: true
  register: graphical
  
- name: Gnome Minimal - Switch to graphical runlevel (Fedora)
  command: systemctl isolate graphical.target
  when: graphical.stdout != "active"
  ignore_errors: true   
      
- name: Gnome Minimal - Disable Wayland (Fedora)
  lineinfile:
    path: /etc/gdm/custom.conf
    regexp: '^#WaylandEnable='
    line: WaylandEnable=false
    state: present
  when: (gnome_minimal.wayland is defined) and (gnome_minimal.wayland|bool == False) 