---
# ansible_role_gnome_minimal/tasks/fedora31.yml
# Author: MTO 
# Description: Minimal installation of Gnome on Fedora31.
#
- name: Gnome Minimal - Update all packages (Fedora31)
  dnf:
    name: "*"
    state: latest

- name: Gnome Minimal - Install Gnome Minimal (Fedora31)
  dnf:
    name:
      - gnome-shell
    state: present    
  
- name: Gnome Minimal - Get default runlevel (Fedora31)
  command: systemctl get-default
  register: runlevel
  
- name: Gnome Minimal - Set graphical runlevel (Fedora31)
  command: systemctl set-default graphical.target
  when: runlevel.stdout != "graphical.target"
  
- name: Gnome Minimal - Is graphical currently active (Fedora31)
  command: systemctl is-active graphical.target
  ignore_errors: true
  register: graphical
  
- name: Gnome Minimal - Switch to graphical runlevel (Fedora31)
  command: systemctl isolate graphical.target
  when: graphical.stdout != "active"
  ignore_errors: true   

- name: Gnome Minimal - Disable Wayland (Fedora31)
  lineinfile:
    path: /etc/gdm/custom.conf
    regexp: '^#WaylandEnable='
    line: WaylandEnable=false
    state: present
  when: gnome_minimal.wayland|bool == False 

- name: Gnome Minimal - Install default packages (Fedora31)
  dnf:
    name: "{{ gnome_minimal.packages }}"
    state: present   

- name: Gnome Minimal - Install Spice Agents in case of VM (Fedora31)
  dnf:
    name:
      - spice-vdagent
      - spice-server
      - spice-glib
      - spice-gtk
    state: present    
  when: (ansible_virtualization_role is defined) and (ansible_virtualization_role != 'host') 