---
# ansible_role_gnome_minimal/tasks/main.yml
# Author: MTO 
# Description: Main file for ansible_role_gnome_minimal
#
- name: Gnome Minimal - Display system, os, version and release 
  debug: 
    msg: "SYSTEM {{ inventory_hostname }} | OS {{ ansible_distribution }} | VERSION {{ ansible_distribution_version }} | RELEASE {{ ansible_distribution_release }}"

- name: Gnome Minimal - Include tasks for installation on Fedora 
  include_tasks: "fedora.yml" 
  when: ansible_distribution == "Fedora"

- name: Gnome Minimal - Unconditionally reboot
  reboot: