---
# ansible_role_gnome_minimal/tasks/main.yml
# Author: MTO 
# Description: Main file for ansible_role_gnome_minimal
#
- name: Gnome Minimal - Display system, os, version and release 
  debug: 
    msg: "SYSTEM {{ inventory_hostname }} | ROLE {{ ansible_virtualization_role }} | OS {{ ansible_distribution }} | VERSION {{ ansible_distribution_version }} | RELEASE {{ ansible_distribution_release }}"

- name: Gnome Minimal - Include vars for OS-specific installation.
  include_vars: "{{ ansible_distribution | lower }}{{ ansible_distribution_version }}.yml"

- name: Gnome Minimal - Include tasks for OS-specific installation.
  include_tasks: "{{ ansible_distribution | lower }}{{ ansible_distribution_version }}.yml" 
 
- name: Gnome Minimal - Unconditionally reboot
  reboot: